/*
 * wifi_setup.c
 * -------------
 * Reads the encrypted device serial number and sets it as the
 * BeaglePlay WiFi Access Point SSID by modifying hostapd.conf.
 *
 * This runs at boot BEFORE hostapd starts, so the AP comes up
 * with the correct serial number as its name.
 *
 * Build (on BeaglePlay):
 *   gcc wifi_setup.c serial_reader.c -o wifi_setup
 *
 * Build (cross-compile on PC for ARM):
 *   arm-linux-gnueabihf-gcc wifi_setup.c serial_reader.c -o wifi_setup
 *
 * Usage:
 *   sudo ./wifi_setup
 *
 * What it does:
 *   1. Reads serial number from encrypted file (./gnss/.sys_cal.dat)
 *   2. If valid: updates ssid= line in /etc/hostapd/hostapd.conf
 *   3. If not found or tampered: uses a fallback SSID
 *   4. Restarts hostapd service to apply changes
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "serial_reader.h"

/* Configuration */
#define HOSTAPD_CONF      "/etc/hostapd/hostapd.conf"
#define HOSTAPD_CONF_TMP  "/etc/hostapd/hostapd.conf.tmp"
#define DEFAULT_SSID       "GNSS-Device-Unconfigured"
#define SSID_PREFIX        ""   /* Set to "GNSS-" if you want a prefix before serial */
#define MAX_LINE           512

/* Update the ssid= line in hostapd.conf */
/* If hostapd.conf doesn't exist, create it with minimal config */
int update_hostapd_ssid(const char *new_ssid) {
    FILE *fin = fopen(HOSTAPD_CONF, "r");

    if (!fin) {
        /* hostapd.conf doesn't exist — create a minimal one */
        printf("[wifi_setup] %s not found, creating with default config...\n", HOSTAPD_CONF);

        /* Make sure /etc/hostapd directory exists */
        system("mkdir -p /etc/hostapd");

        FILE *fout = fopen(HOSTAPD_CONF, "w");
        if (!fout) {
            fprintf(stderr, "ERROR: Cannot create %s\n", HOSTAPD_CONF);
            return -1;
        }
        fprintf(fout, "# Auto-generated by wifi_setup\n");
        fprintf(fout, "interface=wlan0\n");
        fprintf(fout, "driver=nl80211\n");
        fprintf(fout, "ssid=%s%s\n", SSID_PREFIX, new_ssid);
        fprintf(fout, "hw_mode=g\n");
        fprintf(fout, "channel=6\n");
        fprintf(fout, "wmm_enabled=0\n");
        fprintf(fout, "macaddr_acl=0\n");
        fprintf(fout, "auth_algs=1\n");
        fprintf(fout, "ignore_broadcast_ssid=0\n");
        fprintf(fout, "wpa=2\n");
        fprintf(fout, "wpa_passphrase=12345678\n");
        fprintf(fout, "wpa_key_mgmt=WPA-PSK\n");
        fprintf(fout, "rsn_pairwise=CCMP\n");
        fclose(fout);
        printf("[wifi_setup] Created %s with SSID: %s%s\n", HOSTAPD_CONF, SSID_PREFIX, new_ssid);
        return 0;
    }

    /* hostapd.conf exists — update the ssid= line */
    FILE *fout = fopen(HOSTAPD_CONF_TMP, "w");
    if (!fout) {
        fprintf(stderr, "ERROR: Cannot create %s\n", HOSTAPD_CONF_TMP);
        fclose(fin);
        return -1;
    }

    char line[MAX_LINE];
    int ssid_found = 0;

    while (fgets(line, sizeof(line), fin)) {
        /* Check if this line is the ssid= directive */
        if (strncmp(line, "ssid=", 5) == 0) {
            fprintf(fout, "ssid=%s%s\n", SSID_PREFIX, new_ssid);
            ssid_found = 1;
        } else {
            fputs(line, fout);
        }
    }

    /* If ssid= line was not found, append it */
    if (!ssid_found) {
        fprintf(fout, "ssid=%s%s\n", SSID_PREFIX, new_ssid);
    }

    fclose(fin);
    fclose(fout);

    /* Replace original with updated file */
    if (rename(HOSTAPD_CONF_TMP, HOSTAPD_CONF) != 0) {
        perror("ERROR: Failed to replace hostapd.conf");
        return -1;
    }

    return 0;
}

int main(void) {
    char serial[64];
    char ssid[64];
    int result;

    printf("[wifi_setup] Reading device serial number...\n");

    result = read_device_serial(serial, sizeof(serial));

    switch (result) {
        case 1:
            /* Valid serial — use as SSID */
            snprintf(ssid, sizeof(ssid), "%s%s", SSID_PREFIX, serial);
            printf("[wifi_setup] Serial found: %s\n", serial);
            break;

        case 0:
            /* Serial not programmed yet */
            snprintf(ssid, sizeof(ssid), "%s", DEFAULT_SSID);
            printf("[wifi_setup] WARNING: Serial number not programmed. Using default SSID.\n");
            break;

        case -1:
            /* Tampered! */
            snprintf(ssid, sizeof(ssid), "%s", DEFAULT_SSID);
            printf("[wifi_setup] ERROR: Serial file tampered! Using default SSID.\n");
            break;

        default:
            snprintf(ssid, sizeof(ssid), "%s", DEFAULT_SSID);
            break;
    }

    printf("[wifi_setup] Setting WiFi SSID to: %s\n", ssid);

    /* Update hostapd.conf */
    if (update_hostapd_ssid(ssid) != 0) {
        fprintf(stderr, "[wifi_setup] FAILED to update hostapd.conf\n");
        return 1;
    }

    printf("[wifi_setup] hostapd.conf updated successfully.\n");
    printf("[wifi_setup] WiFi AP SSID set to: %s\n", ssid);
    printf("[wifi_setup] hostapd will use this SSID when it starts.\n");

    return 0;
}